### PR TITLE
Open in Mapillary

### PR DESCRIPTION
**Pull request by freenerd**
Fixes https://github.com/Project-OSRM/osrm-frontend/issues/181
Mirrors https://github.com/Project-OSRM/osrm-frontend/pull/197

Todo:
- [x] Nicer pictogram. @TheMarex how did you make yours?

/cc @daniel-j-h

### CODE REVIEW

**Comment by daniel-j-h** [comment]
:bowing_man:

**Comment by TheMarex** [comment]
@freenerd I'm an inkscape wizard. I can quickly add one.

**Comment by TheMarex** [comment]
Should have a pictogram now.

**Comment by freenerd** [comment]
Thanks you, Mr Wizard

**Pull request merged**
