### PR TITLE
Fix legacy url links that don't contain center points

### PR DESCRIPTION
**Pull request by amyleew**
Closes https://github.com/Project-OSRM/osrm-frontend-v2/issues/148.

Next actions:
- [x] pull in start and end points from the query ([src/index.js#L35-L50](https://github.com/Project-OSRM/osrm-frontend-v2/blob/abb8aa7c95b9326b5c742e99fb79df5d66053ad5/src/index.js#L35-L50))
- [x] [pass as waypoint values](https://github.com/Project-OSRM/osrm-frontend-v2/blob/gh-pages/src/index.js#L197) ([src/index.js#L39-L46](https://github.com/Project-OSRM/osrm-frontend-v2/blob/94b9c44956b09591978b270f288925d194f34f7a/src/index.js#L39-L46) & [src/index.js#L49-L54](https://github.com/Project-OSRM/osrm-frontend-v2/blob/94b9c44956b09591978b270f288925d194f34f7a/src/index.js#L49-L54))
- [x] then force [update of center point](https://github.com/Project-OSRM/osrm-frontend-v2/blob/gh-pages/src/index.js#L197) ([src/index.js#L48](https://github.com/Project-OSRM/osrm-frontend-v2/blob/94b9c44956b09591978b270f288925d194f34f7a/src/index.js#L48))
- [x] drop marker at new waypoints
- [x] add if clause for legacy url format ... around here [src/index.js#L34](https://github.com/Project-OSRM/osrm-frontend-v2/blob/94b9c44956b09591978b270f288925d194f34f7a/src/index.js#L34)

cc @tristen

### CODE REVIEW

**Comment by tristen** [comment]
I strongly recommend using a module for parsing query params. Adding conditions for legacy formats is brittle and will break when you need to account for other things. Query params in URLs are by design flexible (i.e. they can be in whatever position they want in a URL).

So use something like https://www.npmjs.com/package/url-querystring which breaks url params into key value pairings which is much more easier to reason with and removes [all this hairy logic in your code](https://github.com/Project-OSRM/osrm-frontend-v2/blob/94b9c44956b09591978b270f288925d194f34f7a/src/index.js#L35-L56).

**Comment by amyleew** [comment]
Thanks @tristen! Cleaned up the code but used the default `browserify` and node.js module  `querystring` instead.

Next to-do is take the query waypoints and put them on the map as markers and populate the `control` input boxes.

**Comment by amyleew** [comment]
Working as expected @tristen. Would you mind a quick code review?

**Comment by amyleew** [comment]
@tristen - Thanks! There is some working going on upstream that's breaking the routing. I'll look into the change once this is all clear.

cc @TheMarex

**Comment by amyleew** [comment]
@tristen - simplified query code based on feedback.

**Pull request merged**
