### PR TITLE
Hightlight names in route steps with bold text

### PR DESCRIPTION
**Pull request by yuryleb**
Highlight way/rotary/destination names in route text instructions with bold:
bold-names-in-steps

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Hm can you check what's going on with master here, we merged and published your changes but it seems like it has no effect on the main site (?)

**Comment by yuryleb** [comment]
I got them locally during #218 rebasing and they work as I could see.

Maybe the changes are not yet reflected to the main site (last time I waited 3-4 days to get merged changes published)?

**Comment by danpat** [comment]
I can see them on the main site:

screen shot 2017-04-01 at 10 26 11 am

`gh-pages` publishing is normally pretty quick (a few minutes), perhaps you are seeing a local cached version?

**Comment by yuryleb** [comment]
I also see new language menu in http://map.project-osrm.org/ but no bold names in route steps. I cleaned browser cache but this had no effect. Looks strange for me too - locally started site has bold names :disappointed:

**Comment by TheMarex** [comment]
Found the problem. Old version of osrm-text-instrucitons in my local node_modules. Works now.

**Comment by yuryleb** [comment]
I see bold names in smartphone browser on main site! The reason was in not really cleaned desktop browser cache IMHO

**Pull request merged**
