### PR TITLE
Change routeDragInterval for less but smoother requests

### PR DESCRIPTION
**Pull request by freenerd**
I was annoyed by osrm-frontend doing so many requests and feeling sluggish therefore on bad connections (like my home 😞).

The best way might be to add a debounce similar to what we have in [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/blob/2fb09050e917de29136331ad9413018f498a9ad1/js/util/util.js#L234)? It would only do a request once the drag has not changed for a bit!?

/cc @perliedman @amyleew

### CODE REVIEW

**Comment by perliedman** [comment]
I guess it would be still as useful if we waited for the waypoint to settle, but wouldn't it also lose the interactive feeling when the route is updated as you drag? On a fast connection, 100ms delay looks _really_ impressive (IMHO).

What happens on a slow connection? I would imagine it would be similar to just having a longer delay, but maybe it's worse than that?

**Comment by freenerd** [comment]
> On a fast connection, 100ms delay looks really impressive (IMHO).

Agreed, but it also creates significant load on the server. Basically with the change here, we can cut requests from the frontend to the demo server by the factor of 5.

> What happens on a slow connection?

Since old requests are not cancelled, but just not used, the pipe gets clogged with requests. Thus it feels overall slower.

**Comment by perliedman** [comment]
FWIW, future versions of LRM will cancel ongoing requests before making a new one. Not entirely sure how much that will affect performance on the server in practice.

**Comment by freenerd** [comment]
@perliedman Cancelling requests will help on the client side, but not on the server side. I ended up only changing the interval to 200ms for now, halfing the number of requests but still feeling snappy-ish enough.

**Pull request merged**
