### PR TITLE
Added French translation

### PR DESCRIPTION
**Pull request by ymoisan**
Hi Folks,

I'd like to have French instructions/directions on map.project-osrm.org so I added a translation for it.  I see instructions/directions are already localized in French in leaflet-routing-machine [1] so I guess it would only be a matter of adding the option to the website.  One thing missing from this PR is a French flag, but I'm sure you have it already.  

Do you think I could get French directions soon on the site ?  I'd like to point to it to my French speaking audience.

TIA

[1] https://github.com/perliedman/leaflet-routing-machine/blob/983201565c7417128c85b6a26b83653902f6cbfe/src/L.Routing.Localization.js

### CODE REVIEW

**Comment by ymoisan** [comment]
Forgot to mention : I do not see what " press enter to drop marker" means, so I translated the way I thought.  In fact, I cannot experience the behaviour mentioned.  Clicking "enter" does nothing (tried in FF and Brave).  I tried adding via points in the top left list with the "+" sign.  I can add points but there is apparently no way of selecting a point (either begin, end or a waypoint) and putting it where we want.  The only way I got adding waypoints to work was by getting beginning and end points first and then drag the route to wherever I wanted a waypoint so it seems to me instructions are out of date.

**Comment by MoKob** [comment]
The "press enter to drop a marker" is referring to a geocoded result. For some reason I currently have to press "enter" twice, but if you enter a location to start a route at, you should be able to press enter to get a marker on the map.

**Comment by daniel-j-h** [comment]
Referencing Press-Enter-Twice issue: https://github.com/Project-OSRM/osrm-frontend/issues/172.

**Comment by ymoisan** [comment]
Thanx folks.  To me "dropping" a marker could mean either to add or delete.  If what is meant is to add a marker, then I would suggest saying so.  Same for delete.  "Drop" is somewhat ambiguous IMO.

Another oddity I'd like to mention : if one manually modifies hl= in the url to anything other than 'de' or 'en' ('fr' for example), then everything is cleared except the base map : no more top left table, righthand-side instructions/directions (understandably) and even no more route.  Couldn't there be a way to be at least show the route (and maybe a short message saying "language X is not supported" ?

Anyhow, let me know when I can try using the site with French.

**Comment by ymoisan** [comment]
I see now.  Enter has to be done _inside_ the text box.  That works fine but indeed one has to hit enter twice.  But then I think the text needs to be clear, like : ""[begin, via, end] - type placename and press enter (twice)" kind of thing.  I really thought I'd be able to select a waypoint added with the "+" sign and then pin it on the map with my mouse (no text added).

**Comment by ymoisan** [comment]
I simplfied the translation so that it could fit in the text box.  See my comment at 4d48d40

**Comment by ymoisan** [comment]
I simplfied the translation so that it could fit in the text box.  See my comment at 4d48d40

**Comment by TheMarex** [comment]
Great! This still needs a flag icon so it is integrated into the frontend. I'll put it on my todo.

**Comment by ymoisan** [comment]
@TheMarex : do you need anything else for this ?  It'd be really cool to have French on the demo map :-).

**Comment by ymoisan** [comment]
@TheMarex : can I do anything else to help you out on this one ?

**Comment by ymoisan** [comment]
@TheMarex : do you still need something for this ticket ?  I'm anxious to see the demo site with French instructions :-)

**Pull request merged**
